# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/zybo_projects/ip_repo/edit_POXI_v1_0.cache/wt [current_project]
set_property parent.project_path c:/zybo_projects/ip_repo/edit_POXI_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/zybo_projects/ip_repo/POXI_1.0
  c:/zybo_projects/ip_repo/TFT_SPI_DISPLAY_240x320_1.0
  c:/zybo_projects/ip_repo/SPI_TFT_DISPLAY_240x320_1.0
  c:/zybo_projects/ip_repo/poxi_2_1.0
} [current_project]
read_vhdl -library xil_defaultlib {
  C:/zybo_projects/ip_repo/POXI_1.0/src/spi.vhd
  c:/zybo_projects/ip_repo/POXI_1.0/hdl/POXI_v1_0_S00_AXI.vhd
  c:/zybo_projects/ip_repo/POXI_1.0/hdl/POXI_v1_0.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top POXI_v1_0 -part xc7z010clg400-1


write_checkpoint -force -noxdef POXI_v1_0.dcp

catch { report_utilization -file POXI_v1_0_utilization_synth.rpt -pb POXI_v1_0_utilization_synth.pb }
